<#
.SYNOPSIS
Uninstalls .NET SDK all versions. 
.DESCRIPTION
This script automates the removal of .NET SDK from a machine completely and silently with no user input and no reboot. 
.NOTES
MicrosoftNET-SDKRemoval.ps1 - V.Ashodhiya - 04-12-2024
Script History:
Version 1.0 - Script inception
Version 1.1 - Added Support for .NET 9.0 and 10.0
Version 1.2 - Added completed .NET inventory to the script.
#>
#---------------------------------------------------------------------#
# Define the path for the log file
$logFilePath = "C:\Windows\fndr\logs"
$logFileName = "$logFilePath\Net-sdkuninstall.log"
# Function to write logs
function Write-Log {
    param (
        [string]$message
    )
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp - $message"
    Write-Output $logMessage
 
    # Ensure log file path exists
    if (-not (Test-Path $logFilePath)) {
        New-Item -Path $logFilePath -ItemType Directory | Out-Null
    }
 
    # Write log message to log file
    Add-Content -Path $logFileName -Value $logMessage
}
# Function to uninstall applications via Win32_Product (WMI)

function Uninstall-WmiApp {
    param (
        [string]$appName
    )
 
    Write-Log "Checking for $appName via WMI..." -Verbose
 
    $installedApps = Get-WmiObject -Query "SELECT * FROM Win32_Product WHERE Name LIKE '%$appName%'"
 
    if ($installedApps.Count -eq 0) {
        Write-Log "$appName not found using WMI." -Verbose
        return $false
    }
    else {
        foreach ($app in $installedApps) {
            try {
                Write-Log "Uninstalling $($app.Name) via WMI..." -Verbose
                $app.Uninstall() | Out-Null
                Write-Log "$($app.Name) has been uninstalled using WMI." -Verbose
            }
            catch {
                Write-Log "Failed to uninstall $($app.Name) via WMI. Error: $_" -ForegroundColor Red
            }
        }
        return $true
    }
}

# Function to uninstall applications via registry

function Uninstall-RegistryApp {
    param (
        [string]$appName
    )
    
    $registryPaths = @(
        "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*"
    )
    
    $appFound = $false

    foreach ($regPath in $registryPaths) {
        $apps = Get-ItemProperty $regPath | Where-Object { $_.DisplayName -like "*$appName*" }

        foreach ($app in $apps) {
            $appFound = $true
            Write-Log "Uninstalling $($app.DisplayName) from the registry..." -Verbose
            
            # Try to read QuietUninstallString first
            $uninstallCmd = if ($app.QuietUninstallString) {
                $app.QuietUninstallString
            }
            else {
                $app.UninstallString
            }

            if ($uninstallCmd) {
                # Use regex to extract text within double quotes
                $uninstallCmd = $uninstallCmd -replace '^.*?"(.*?)".*$', '$1'
                
                Write-Log "Using '$uninstallCmd' to remove Application" -Verbose
                try {
                    # Execute the uninstall command
                    Start-Process -FilePath $uninstallCmd -ArgumentList "/uninstall", "/quiet" -Wait -NoNewWindow
                    Write-Log "$($app.DisplayName) has been uninstalled using the registry." -Verbose
                }
                catch {
                    Write-Log "Failed to uninstall $($app.DisplayName). Error: $_" -ForegroundColor Red
                }
            }
            else {
                Write-Log "Uninstall string not found for $($app.DisplayName)." -ForegroundColor Yellow
            }
        }
    }

    if (-not $appFound) {
        Write-Log "$appName not found in the registry." -Verbose
    }
    return $appFound
}

# Main uninstall function combining both methods

function Uninstall-Application {
    param (
        [string]$appName
    )
    
    $uninstalled = $false

    # Try to uninstall via WMI first
    $uninstalled = Uninstall-RegistryApp $appName

    # If not found via WMI, try via the registry
    if (-not $uninstalled) {
        Uninstall-WmiApp $appName
    }
}

# From SQL
Uninstall-Application "Microsoft .NET Host - 10.0.0 (x64)"
Uninstall-Application "Microsoft .NET Host - 10.0.0 (x86)"
Uninstall-Application "Microsoft .NET Host - 10.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host - 10.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host - 10.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host - 10.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host - 10.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host - 10.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host - 10.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host - 10.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host - 5.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.11 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.12 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.12 (x86)"
Uninstall-Application "Microsoft .NET Host - 5.0.13 (x86)"
Uninstall-Application "Microsoft .NET Host - 5.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.15 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.17 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.17 (x86)"
Uninstall-Application "Microsoft .NET Host - 5.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host - 5.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host - 5.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host - 5.0.9 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.0 Preview 7 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.20 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.22 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.23 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.25 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.26 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.27 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.28 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.28 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.32 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.33 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.33 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.35 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.36 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.36 (x86)"
Uninstall-Application "Microsoft .NET Host - 6.0.6 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host - 6.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host - 7.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.14 (x86)"
Uninstall-Application "Microsoft .NET Host - 7.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host - 7.0.20 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.20 (x86)"
Uninstall-Application "Microsoft .NET Host - 7.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host - 7.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host - 7.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host - 7.0.9 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.11 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.11 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.12 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.12 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.13 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.13 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.14 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.15 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.15 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.16 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.16 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.17 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.17 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.18 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.18 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.19 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.19 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.20 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.20 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.21 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.21 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.22 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.22 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.23 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.23 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.24 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.24 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.25 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.25 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.5 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.6 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.6 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host - 8.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host - 8.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.0 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.0 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.11 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.11 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.12 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.12 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.13 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.13 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.14 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.5 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.6 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.6 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host - 9.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host - 9.0.9 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.0 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.0 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 10.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.11 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.12 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.12 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.13 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.13 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.15 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.15 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.17 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.17 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 5.0.9 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.0 Preview 7 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.20 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.22 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.23 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.25 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.25 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.26 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.27 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.28 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.28 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.29 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.30 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.30 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.32 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.32 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.33 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.33 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.35 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.35 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.36 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.36 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.6 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.6 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 6.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.14 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.19 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.20 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.20 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 7.0.9 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.11 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.11 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.12 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.12 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.13 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.13 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.14 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.15 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.15 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.16 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.16 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.17 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.17 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.18 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.18 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.19 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.19 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.20 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.20 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.21 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.21 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.22 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.22 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.23 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.23 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.24 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.24 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.25 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.25 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.5 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.6 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.6 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 8.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.0 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.0 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.1 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.1 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.10 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.10 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.11 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.11 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.12 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.12 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.13 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.13 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.14 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.14 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.2 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.2 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.3 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.3 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.4 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.4 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.5 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.5 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.6 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.6 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.7 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.7 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.8 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.8 (x86)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.9 (x64)"
Uninstall-Application "Microsoft .NET Host FX Resolver - 9.0.9 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.0 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.0 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.1 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.1 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.2 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.2 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.3 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.3 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.4 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 10.0.4 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.1 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.1 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.10 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.10 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.11 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.12 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.12 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.13 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.13 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.14 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.15 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.15 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.17 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.17 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.3 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.3 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.7 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.7 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.8 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.8 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.9 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 5.0.9 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.0 Preview 7 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.1 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.1 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.10 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.10 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.13 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.13 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.14 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.14 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.20 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.20 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.21 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.21 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.22 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.23 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.25 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.25 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.26 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.26 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.27 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.27 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.28 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.28 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.29 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.3 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.30 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.30 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.31 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.31 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.32 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.32 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.33 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.33 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.35 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.35 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.36 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.36 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.5 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.6 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.6 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.7 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.7 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.8 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.8 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 6.0.9 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.10 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.10 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.14 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.14 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.16 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.16 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.17 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.17 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.19 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.19 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.2 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.2 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.20 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.20 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.3 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.3 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.4 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.4 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.5 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.7 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.9 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 7.0.9 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.1 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.1 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.10 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.10 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.11 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.11 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.12 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.12 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.13 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.13 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.14 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.14 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.15 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.15 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.16 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.16 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.17 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.17 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.18 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.18 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.19 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.19 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.2 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.2 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.20 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.20 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.21 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.21 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.22 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.22 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.23 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.23 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.24 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.24 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.25 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.25 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.3 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.3 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.4 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.4 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.5 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.5 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.6 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.6 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.7 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.7 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.8 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 8.0.8 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.0 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.0 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.1 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.1 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.10 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.10 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.11 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.11 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.12 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.12 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.13 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.13 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.14 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.14 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.2 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.2 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.3 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.3 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.4 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.4 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.5 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.5 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.6 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.6 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.7 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.7 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.8 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.8 (x86)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.9 (x64)"
Uninstall-Application "Microsoft .NET Runtime - 9.0.9 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.0 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.0 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.1 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.1 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.2 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.2 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.3 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.3 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.4 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 10.0.4 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.0.1 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.0.3 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.0 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.10 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.10 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.12 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.12 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.16 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.16 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.19 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.19 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.20 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.20 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.23 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.23 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.24 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.24 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.25 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.25 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.26 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.26 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.27 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.27 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.28 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.28 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.30 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.30 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.32 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.32 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.8 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.8 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.9 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 3.1.9 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.1 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.1 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.10 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.10 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.11 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.12 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.12 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.13 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.13 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.15 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.15 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.17 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.17 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.3 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.3 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.7 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 5.0.7 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.0 Preview 7 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.1 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.1 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.10 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.10 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.13 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.13 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.14 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.14 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.20 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.20 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.21 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.21 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.22 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.23 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.25 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.25 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.26 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.26 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.27 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.27 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.28 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.28 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.29 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.3 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.30 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.30 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.31 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.31 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.32 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.32 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.33 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.33 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.35 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.35 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.36 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.36 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.5 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.6 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.6 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.7 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.7 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.8 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 6.0.8 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.10 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.10 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.14 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.14 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.16 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.16 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.17 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.17 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.19 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.19 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.2 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.2 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.20 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.20 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.3 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.3 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.5 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.7 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.9 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 7.0.9 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.1 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.1 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.10 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.10 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.11 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.11 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.12 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.12 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.13 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.13 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.14 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.14 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.15 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.15 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.16 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.16 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.17 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.17 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.18 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.18 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.19 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.19 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.2 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.2 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.20 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.20 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.21 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.21 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.22 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.22 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.23 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.23 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.24 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.24 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.25 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.25 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.3 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.3 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.4 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.4 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.5 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.5 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.6 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.6 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.7 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.7 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.8 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 8.0.8 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.0 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.0 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.1 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.1 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.10 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.10 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.11 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.11 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.12 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.12 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.13 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.13 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.14 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.14 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.2 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.2 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.3 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.3 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.4 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.4 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.5 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.5 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.6 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.6 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.7 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.7 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.8 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.8 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.9 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime - 9.0.9 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime 10.0.0 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime 10.0.0 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime 10.0.2 (x64)"
Uninstall-Application "Microsoft Windows Desktop Runtime 10.0.2 (x86)"
Uninstall-Application "Microsoft Windows Desktop Runtime 10.0.3 (x64)"
